"%dev":
  quarkus:
    datasource:
      db-kind: h2
      username: sa
      password: sa
      jdbc:
        url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hibernate-orm:
      schema-management:
        strategy: drop-and-create

"%test":
  quarkus:
    datasource:
      db-kind: h2
      username: sa
      password: sa
      jdbc:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hibernate-orm:
      schema-management:
        strategy: drop-and-create

greeting:
  message: "hello"
